export const mockLogin = '\n'
  + '--uuid:3237ee2e-9e56-4d2d-ada9-9ea299b0fdc9\n'
  + 'Content-Type: application/xop+xml; charset=UTF-8; type="text/xml";\n'
  + 'Content-Transfer-Encoding: binary\n'
  + 'Content-ID: <root.message@cxf.apache.org>\n'
  + '\n'
  + '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:getAuthentificationFrontResponse xmlns:ns2="http://ws.icl.veolia.com/"><return><espaceClient><cptAuth>N</cptAuth><cptDLastcon>2024-01-25T18:00:00+01:00</cptDLastcon><cptEmail>email@example.com</cptEmail><cptFlgPwdValide>O</cptFlgPwdValide><cptNumero>12345</cptNumero><cptPwd>12345</cptPwd><cptTel06>0606060606</cptTel06><flagNewsletter>N</flagNewsletter><flagNewsletterLocal>N</flagNewsletterLocal></espaceClient><listContrats><aboId>12345</aboId><aboRefcli>12345</aboRefcli><acpComquar>12345</acpComquar><acpInsee>12345</acpInsee><acpLibperso>STREET</acpLibperso><acpNumero>12345</acpNumero><CLibcom>CITY</CLibcom><CReg>14</CReg><CTraitegn>600</CTraitegn><casRdv>0</casRdv><cliLibcourtciv>M</cliLibcourtciv><cliNom>JOHN DOE</cliNom><clientAbo><cliCodepostal>12345</cliCodepostal><cliCommune>CITY</cliCommune><cliId>12345</cliId><cliLibcourtciv>M</cliLibcourtciv><cliNom>JOHN DOE</cliNom><cliNomvoie>STREET</cliNomvoie><cliNumvoie>10</cliNumvoie></clientAbo><clientPay><cliCodepostal>12345</cliCodepostal><cliCommune>CITY</cliCommune><cliId>12345</cliId><cliLibcourtciv>M</cliLibcourtciv><cliNom>JOHN DOE</cliNom><cliNomvoie>STREET</cliNomvoie><cliNumvoie>10</cliNumvoie></clientPay><contratMigre>false</contratMigre><cptNumero>12345</cptNumero><hpCodePostal>12345</hpCodePostal><hpDpt>12</hpDpt></listContrats></return></ns2:getAuthentificationFrontResponse></soap:Body></soap:Envelope>\n'
  + '--uuid:3237ee2e-9e56-4d2d-ada9-9ea299b0fdc9--\n'
export const mockEnergyData = '\n'
  + '--uuid:8ad230ff-7d22-45bf-9e5e-19161316f835\n'
  + 'Content-Type: application/xop+xml; charset=UTF-8; type="text/xml";\n'
  + 'Content-Transfer-Encoding: binary\n'
  + 'Content-ID: <root.message@cxf.apache.org>\n'
  + '\n'
  + '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:getConsommationJournaliereResponse xmlns:ns2="http://ws.icl.veolia.com/"><return><codeRetour>00</codeRetour><consommation>200</consommation><dateReleve>2023-10-26T00:00:00+02:00</dateReleve><fiabiliteIndex>M</fiabiliteIndex><index>34374</index></return><return><codeRetour>00</codeRetour><consommation>142</consommation><dateReleve>2023-10-29T00:00:00+02:00</dateReleve><fiabiliteIndex>M</fiabiliteIndex><index>34574</index></return></ns2:getConsommationJournaliereResponse></soap:Body></soap:Envelope>\n'
  + '--uuid:8ad230ff-7d22-45bf-9e5e-19161316f835--'
